# Copyright 2026 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any, ClassVar, Protocol

from wazo_chatd.connectors.delivery import DeliveryStatus
from wazo_chatd.connectors.types import (
    InboundMessage,
    OutboundMessage,
    StatusUpdate,
    TransportData,
)


class Connector(Protocol):
    """Technology-agnostic protocol for messaging backends.

    A Connector handles communication with a single external messaging
    system.  It is intentionally free of framework types (no HTTP, no
    Flask) and has no database access — the router/service layer handles
    persistence.

    Transport-agnostic: works with webhooks, polling, websockets, or any
    other inbound mechanism.

    See ``wazo_chatd.connectors.backends.internal`` for a self-documenting
    reference implementation.
    """

    backend: ClassVar[str]
    """Unique backend identifier, e.g. ``"twilio"``, ``"vonage"``."""

    supported_types: ClassVar[tuple[str, ...]]
    """Connector types this backend can handle, e.g. ``("sms", "mms", "whatsapp")``."""

    status_map: ClassVar[dict[str, DeliveryStatus]]
    """Mapping of provider-specific status strings to internal DeliveryStatus.

    Only statuses that should create a DeliveryRecord need to be mapped.
    Transient statuses (e.g. ``"queued"``, ``"sending"``) should be
    omitted — the executor ignores unmapped statuses.

    Example::

        status_map = {
            'sent': DeliveryStatus.SENT,
            'delivered': DeliveryStatus.DELIVERED,
            'failed': DeliveryStatus.FAILED,
        }
    """

    def configure(
        self,
        type_: str,
        provider_config: Mapping[str, Any],
        connector_config: Mapping[str, Any],
    ) -> None:
        """Initialize the connector with two configuration sources.

        Args:
            type_: Which messaging type this instance handles
                (from ``ChatProvider.type_``).
            provider_config: Per-tenant configuration from
                ``ChatProvider.configuration`` JSONB (credentials, etc.
                — managed by confd).
            connector_config: System-level configuration from
                ``/etc/wazo-chatd/conf.d/`` (polling interval, inbound
                mode, network settings).

        Must be reconstructable from these arguments alone, as the same
        arguments are serialized over the pipe to the server process.
        """
        ...

    def send(self, message: OutboundMessage) -> str:
        """Send a message through this connector's external API.

        Returns:
            An external message ID for tracking and idempotency.

        Raises:
            ConnectorSendError: If the send fails.

        May be sync or async.  The :class:`DeliveryExecutor` (async)
        wraps sync implementations with ``asyncio.to_thread()``.
        Connectors that use async HTTP clients (httpx, aiohttp) can
        implement this as a coroutine for better performance.

        Idempotency (optional):
            ``message.metadata`` may contain ``idempotency_key``
            (generated by the router, stable across retries).  If the
            provider supports idempotent requests (e.g. Twilio's
            ``Idempotency-Key`` header), pass this key to prevent
            duplicate sends on retries.
        """
        ...

    def can_handle(self, data: TransportData) -> bool:
        """Check whether this connector can handle the given event data.

        A lightweight pre-filter called before :meth:`on_event`.  Should
        inspect transport-specific metadata (e.g. headers for webhooks)
        without doing full parsing or signature validation.

        Use structural pattern matching to dispatch by transport type::

            match data:
                case WebhookData(headers=headers):
                    return 'X-My-Signature' in headers
                case _:
                    return True

        Returns:
            ``True`` if this connector should attempt to handle the event.
        """
        ...

    def on_event(self, data: TransportData) -> InboundMessage | StatusUpdate | None:
        """Parse and validate an incoming event from any transport.

        Use structural pattern matching to dispatch by transport type::

            match data:
                case WebhookData(body=body, headers=headers):
                    ...validate signature, parse body...
                case PollData(body=body):
                    ...parse polled data...

        Returns:
            An :class:`InboundMessage` for new messages, a
            :class:`StatusUpdate` for delivery status changes,
            or ``None`` to skip (e.g. irrelevant event).

        Auth/signature validation is the connector's responsibility.

        Idempotency (optional):
            If the provider supplies an idempotency key, include it in
            ``InboundMessage.metadata`` as ``idempotency_key``.  The
            router uses this to deduplicate inbound messages via a
            GIN-indexed JSONB lookup on ``MessageMeta.extra``.  If the
            key is absent, no dedup is performed — the message is
            always accepted.
        """
        ...

    def listen(self, on_message: Callable[[InboundMessage], None]) -> None:
        """Begin listening for incoming messages via connector-controlled transports.

        For polling:
            Start a loop, wrap results in :class:`PollData`, call
            :meth:`on_event`, forward non-None results to *on_message*.

        For webhook-only connectors:
            No-op — chatd's HTTP adapter calls :meth:`on_event` directly.
        """
        ...

    def stop(self) -> None:
        """Stop listening and clean up resources."""
        ...

    def normalize_identity(self, raw_identity: str) -> str:
        """Normalize an external identity to its canonical form.

        Examples: phone number to E.164 format, email to lowercase.

        Raises:
            ValueError: If the identity does not match this connector's
                expected format.

        Also used for capability resolution: if this method succeeds for
        a given identity, this connector type can reach that participant.
        """
        ...
