# Copyright 2026 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any, ClassVar, Protocol

from wazo_chatd.connectors.types import InboundMessage, OutboundMessage


class Connector(Protocol):
    """Technology-agnostic protocol for messaging backends.

    A Connector handles communication with a single external messaging
    system.  It is intentionally free of framework types (no HTTP, no
    Flask) and has no database access — the router/service layer handles
    persistence.

    Transport-agnostic: works with webhooks, polling, websockets, or any
    other inbound mechanism.

    See ``wazo_chatd.connectors.backends.internal`` for a self-documenting
    reference implementation.
    """

    backend: ClassVar[str]
    """Unique backend identifier, e.g. ``"twilio"``, ``"vonage"``."""

    supported_types: ClassVar[tuple[str, ...]]
    """Connector types this backend can handle, e.g. ``("sms", "mms", "whatsapp")``."""

    def configure(
        self,
        type_: str,
        provider_config: Mapping[str, Any],
        connector_config: Mapping[str, Any],
    ) -> None:
        """Initialize the connector with two configuration sources.

        Args:
            type_: Which messaging type this instance handles
                (from ``ChatProvider.type_``).
            provider_config: Per-tenant configuration from
                ``ChatProvider.configuration`` JSONB (credentials, etc.
                — managed by confd).
            connector_config: System-level configuration from
                ``/etc/wazo-chatd/conf.d/`` (polling interval, inbound
                mode, network settings).

        Must be reconstructable from these arguments alone, as the same
        arguments are serialized over the pipe to the server process.
        """
        ...

    def send(self, message: OutboundMessage) -> str:
        """Send a message through this connector's external API.

        Returns:
            An external message ID for tracking and idempotency.

        Raises:
            ConnectorSendError: If the send fails.

        May be sync or async.  The :class:`DeliveryExecutor` (async)
        wraps sync implementations with ``asyncio.to_thread()``.
        Connectors that use async HTTP clients (httpx, aiohttp) can
        implement this as a coroutine for better performance.

        Idempotency (optional):
            ``message.metadata`` may contain ``idempotency_key``
            (generated by the router, stable across retries).  If the
            provider supports idempotent requests (e.g. Twilio's
            ``Idempotency-Key`` header), pass this key to prevent
            duplicate sends on retries.
        """
        ...

    def on_event(
        self,
        transport: str,
        raw_data: Mapping[str, Any],
    ) -> InboundMessage | None:
        """Parse and validate an incoming event from any transport.

        Args:
            transport: How the data arrived — ``'webhook'``, ``'poll'``,
                ``'websocket'``, etc.
            raw_data: Plain dict extracted by the caller (no framework
                types).

        Returns:
            An :class:`InboundMessage` if valid, or ``None`` to skip
            (e.g. a status callback, not a message).

        Called by:

        - chatd's shared HTTP adapter for webhooks
          (``POST /connectors/incoming/<backend>``)
        - The connector itself inside :meth:`listen` for poll/websocket
          results

        Auth/signature validation is the connector's responsibility.

        Idempotency (optional):
            If the provider supplies an idempotency key (e.g. Twilio's
            ``I-Twilio-Idempotency-Token`` header), include it in
            ``InboundMessage.metadata`` as ``idempotency_key``.  The
            router uses this to deduplicate inbound messages via a
            GIN-indexed JSONB lookup on ``MessageMeta.extra``.  If the
            key is absent, no dedup is performed — the message is
            always accepted.
        """
        ...

    def listen(self, on_message: Callable[[InboundMessage], None]) -> None:
        """Begin listening for incoming messages via connector-controlled transports.

        For polling:
            Start a loop, call :meth:`on_event` with ``'poll'`` for each
            result, forward non-None results to *on_message*.

        For websocket:
            Open a connection, call :meth:`on_event` with ``'websocket'``
            for each frame, forward to *on_message*.

        For webhook-only connectors:
            No-op — chatd's HTTP adapter calls :meth:`on_event` directly.
        """
        ...

    def stop(self) -> None:
        """Stop listening and clean up resources."""
        ...

    def normalize_identity(self, raw_identity: str) -> str:
        """Normalize an external identity to its canonical form.

        Examples: phone number to E.164 format, email to lowercase.

        Raises:
            ValueError: If the identity does not match this connector's
                expected format.

        Also used for capability resolution: if this method succeeds for
        a given identity, this connector type can reach that participant.
        """
        ...
