# Copyright 2026 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class OutboundMessage:
    """A message to be sent through a connector to an external system."""

    sender_alias: str
    """Sender's external identity from UserAlias (e.g. "+15551234")."""

    recipient_alias: str
    """Recipient's external identity from RoomUser.identity (e.g. "+15559876")."""

    sender_uuid: str
    """Internal Wazo user UUID, for tracking."""

    body: str
    """Message content."""

    delivery_uuid: str
    """MessageMeta.message_uuid — links back to the delivery record in DB."""

    metadata: Mapping[str, Any] = field(default_factory=dict)
    """Connector-specific extra data.

    May contain ``idempotency_key`` (generated by the router, stable
    across retries) for providers that support idempotent requests.
    """


@dataclass(frozen=True)
class InboundMessage:
    """A message received from an external system through a connector."""

    sender: str
    """External identity of the sender (phone number, email, etc.)."""

    recipient: str
    """External identity of the recipient."""

    body: str
    """Message content."""

    backend: str
    """Which backend produced this message (e.g. "twilio")."""

    external_id: str
    """The backend's message ID, for idempotency and tracking."""

    metadata: Mapping[str, Any] = field(default_factory=dict)
    """Backend-specific extra data.

    If the provider supplies an idempotency key, include it as
    ``idempotency_key``.  The router uses this to deduplicate inbound
    messages via a GIN-indexed JSONB lookup on MessageMeta.extra.
    """


@dataclass
class ConfigSync:
    """Sent via pipe during server process initialization.

    Contains the full list of provider configurations so the server
    process can reconstruct connector instances without DB access.
    """

    providers: list[dict[str, Any]]


@dataclass
class ConfigUpdate:
    """Sent via pipe at runtime when a provider configuration changes."""

    action: str
    """One of 'add', 'update', 'remove'."""

    provider: dict[str, Any]
