# Copyright 2026 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping
from typing import Any, ClassVar, Protocol

from wazo_chatd.database.delivery import DeliveryStatus
from wazo_chatd.plugins.connectors.types import (
    InboundMessage,
    OutboundMessage,
    StatusUpdate,
    TransportData,
)


class Connector(Protocol):
    """Technology-agnostic protocol for messaging backends.

    A Connector handles communication with a single external messaging
    system.  It is intentionally free of framework types (no HTTP, no
    Flask) and has no database access — the router/service layer handles
    persistence.

    Transport-agnostic: works with webhooks, polling, websockets, or any
    other inbound mechanism.

    See ``wazo_chatd.plugins.connectors.backends.internal`` for a self-documenting
    reference implementation.
    """

    backend: ClassVar[str]
    """Unique backend identifier, e.g. ``"twilio"``, ``"vonage"``."""

    supported_types: ClassVar[tuple[str, ...]]
    """Connector types this backend can handle, e.g. ``("sms", "mms", "whatsapp")``."""

    status_map: ClassVar[dict[str, DeliveryStatus]]
    """Mapping of provider-specific status strings to internal DeliveryStatus.

    Only statuses that should create a DeliveryRecord need to be mapped.
    Transient statuses (e.g. ``"queued"``, ``"sending"``) should be
    omitted — the executor ignores unmapped statuses.

    Example::

        status_map = {
            'sent': DeliveryStatus.SENT,
            'delivered': DeliveryStatus.DELIVERED,
            'failed': DeliveryStatus.FAILED,
        }
    """

    verifies_signatures: ClassVar[bool]
    """Whether this backend authenticates inbound events via signature.

    Must be ``True`` for backends handling webhook traffic from
    untrusted networks (external SMS/messaging providers). Set
    ``False`` only for trusted transports (internal, tests, polling).

    When ``True``, :meth:`verify_signature` is called before
    :meth:`on_event`'s result is enqueued — a falsy return or a
    raised exception causes :class:`ConnectorAuthException` (HTTP 401).
    When ``False``, :meth:`verify_signature` is not called and may be
    omitted entirely.
    """

    def __init__(
        self,
        tenant_uuid: str,
        provider_config: Mapping[str, Any],
        connector_config: Mapping[str, Any],
    ) -> None:
        """Initialize the connector with tenant scope and configuration.

        Args:
            tenant_uuid: Identifies the tenant this instance serves.
                One instance per (tenant_uuid, backend); the store
                reconstructs the instance when provider_config changes.
                Used for self-identification in logs, metrics, and
                outbound messages emitted by poll/listen modes.
            provider_config: Per-tenant configuration from wazo-auth
                external auth config (credentials, API keys — managed
                via ``PUT /external/{backend}/config``).
            connector_config: System-level configuration from
                ``/etc/wazo-chatd/conf.d/`` (polling interval, inbound
                mode, network settings).

        Lifecycle contract: one instance per (tenant_uuid, backend),
        reconstructed whenever provider_config changes (credential
        rotation, TTL expiry). Do not put process-global state in
        ``__init__``; class-level attributes (e.g. shared HTTP pools)
        are the right place for cross-tenant resources.
        """
        ...

    def send(self, message: OutboundMessage) -> str:
        """Send a message through this connector's external API.

        Returns:
            An external message ID for tracking and idempotency.

        Raises:
            ConnectorSendError: If the send fails.

        May be sync or async.  The :class:`DeliveryExecutor` (async)
        wraps sync implementations with ``asyncio.to_thread()``.
        Connectors that use async HTTP clients (httpx, aiohttp) can
        implement this as a coroutine for better performance.

        Idempotency (optional):
            ``message.metadata`` may contain ``idempotency_key``
            (generated by the router, stable across retries).  If the
            provider supports idempotent requests (e.g. Twilio's
            ``Idempotency-Key`` header), pass this key to prevent
            duplicate sends on retries.
        """
        ...

    @classmethod
    def can_handle(cls, data: TransportData) -> bool:
        """Check whether this connector can handle the given event data.

        A lightweight pre-filter called before :meth:`on_event`.  Should
        inspect transport-specific metadata (e.g. headers for webhooks)
        without doing full parsing or signature validation.

        Returns:
            ``True`` if this connector should attempt to handle the event.
        """
        ...

    def verify_signature(self, data: TransportData) -> bool:
        """Verify that an inbound event is authentic.

        Called by the router when :attr:`verifies_signatures` is
        ``True``, before :meth:`on_event`'s result is enqueued for
        async processing. Instance method — has access to per-tenant
        credentials loaded in :meth:`__init__`.

        Returns:
            ``True`` if the event is authentic, ``False`` to reject.
            A ``False`` return causes the router to raise
            :class:`ConnectorAuthException` (HTTP 401).

        For webhook-based providers, implement HMAC verification
        using the signature header.

        Backends with :attr:`verifies_signatures` = ``False`` may
        omit this method entirely.
        """
        ...

    @classmethod
    def on_event(cls, data: TransportData) -> InboundMessage | StatusUpdate | None:
        """Parse an incoming event from any transport.

        Returns:
            An :class:`InboundMessage` for new messages, a
            :class:`StatusUpdate` for delivery status changes,
            or ``None`` to skip (e.g. irrelevant event).

        Idempotency (optional):
            If the provider supplies an idempotency key, include it in
            ``InboundMessage.metadata`` as ``idempotency_key``.
        """
        ...

    def scan_inbound(self) -> list[InboundMessage]:
        """Return new inbound messages since the last scan.

        Sync or async. Sync implementations are wrapped with
        ``asyncio.to_thread`` by the delivery loop. Async
        implementations (``httpx.AsyncClient``, ``aiohttp``) avoid
        the thread hop.

        Called periodically by the delivery loop when ``mode=poll``.
        The connector owns its cursor internally (timestamp, last
        external_id) — callers pass no arguments. Must not block
        longer than the provider HTTP timeout.

        Exceptions propagate; the delivery loop logs and schedules
        the next cycle at the previous interval. Backends without
        an inbound polling API may return ``[]``.
        """
        ...

    def track_outbound(self, external_ids: Iterable[str]) -> list[StatusUpdate]:
        """Return current status for each outbound ``external_id``.

        Sync or async. Sync implementations are wrapped with
        ``asyncio.to_thread`` by the delivery loop.

        The delivery loop passes external_ids of outbound messages
        whose latest :class:`DeliveryRecord` is still in a
        non-terminal state. Implementations must be efficient with
        large batches (hundreds of IDs) — prefer bulk endpoints
        when the provider offers them.

        Backends that receive status via webhook callbacks may
        leave this as a no-op (return ``[]``).
        """
        ...

    async def listen(
        self, on_message: Callable[[InboundMessage | StatusUpdate], None]
    ) -> None:
        """Run as an asyncio task on the dedicated listen loop.

        Async-only — a sync ``listen`` blocks the event loop and
        starves every peer listener on the same thread. Backends
        with sync-only transport libraries must wrap themselves:
        ``await asyncio.to_thread(self._blocking_listen_forever)``.

        Use async I/O: ``aiohttp`` for websockets, ``aio-pika`` for
        AMQP, ``asyncio.DatagramProtocol`` for UDP.

        Per-message work must be minimal (parse + forward). Heavy
        processing happens downstream on the delivery loop after
        ``on_message`` has enqueued the result.

        Task cancellation is the shutdown signal — clean up in
        ``finally``. Reconnect loops must use jittered backoff to
        avoid thundering-herd storms when many tenants reconnect
        after a network blip.
        """
        ...

    def stop(self) -> None:
        """Hint-only cleanup for listener resources.

        The canonical shutdown mechanism is task cancellation; the
        delivery loop cancels the ``listen`` task at shutdown.
        This method exists for backends that hold external
        resources that cancellation alone cannot release.
        """
        ...

    @classmethod
    def normalize_identity(cls, raw_identity: str) -> str:
        """Normalize an external identity to its canonical form.

        Examples: phone number to E.164 format, email to lowercase.

        Raises:
            ValueError: If the identity does not match this connector's
                expected format.

        Also used for capability resolution: if this method succeeds for
        a given identity, this connector type can reach that participant.
        """
        ...
