# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files to the extra_config_files directory to override
# the settings in this file

# Directory in which to place config overrides
extra_config_files: '/etc/wazo-chatd/conf.d'

debug: false
log_level: info
log_file: /var/log/wazo-chatd.log

# REST API server
rest_api:

  # Address to listen on
  listen: 127.0.0.1

  # Port to listen on
  port: 9304

  # CORS configuration. See Flask-CORS documentation for other values.
  cors:

    # Enabled by default
    enabled: True

    # Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token, Wazo-Tenant]

  # Maximum of concurrent threads processing requests
  # See the performance documentation for more details
  # https://wazo-platform.org/uc-doc/system/performance/
  max_threads: 10

# Authentication server connection settings
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false

# wazo-amid connection settings
amid:
  host: localhost
  port: 9491
  prefix: null
  https: false

# Confd connection settings
confd:
  host: localhost
  port: 9486
  prefix: null
  https: false
  timeout: 90

# Event bus (AMQP) connection settings
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: wazo-headers

enabled_plugins:
  api: true
  config: true
  status: true
  presences: true

service_discovery:
  enabled: false

# Example settings to enable service discovery
#
# Necessary to use service discovery
# consul:
#   scheme: http
#   host: consul.example.com
#   port: 8500
#   token: 'the_one_ring'
#
# # All time intervals are in seconds
# service_discovery:
#   # Indicates whether of not to use service discovery.
#   enabled: true
#   # The address that will be received by other services using service discovery.
#   # Use "advertise_address: auto" to enable ip address detection based on
#   # advertise_address_interface
#   advertise_address: auto
#   # If advertise_address is "auto" this interface will be used to find the ip
#   # address to advertise. Ignored otherwise
#   advertise_address_interface: eth0
#   advertise_port: 9304
#   # The number of seconds that consul will wait between 2 ttl messages to mark
#   # this service as up
#   ttl_interval: 30
#   # The time interval before the service sends a new ttl message to consul
#   refresh_interval: 27
#   # The time interval to detect that the service is running when starting
#   retry_interval: 2
#   extra_tags: []
